version: '3'
services:
  store:
    image: samply/samply.store:0.2.1-alpha-3
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASS: samplystore
    networks:
    - gba
    ports:
    - "8080:8080"
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: samplystore
      POSTGRES_PASSWORD: samplystore
    networks:
    - gba
    ports:
    - "5432:5432"
networks:
  gba:
    driver: bridge
