version: '3.2'
services:
  store:
    image: samply/samply.store:4.2.5
    environment:
      POSTGRES_HOST: store-db
      POSTGRES_PASS: samplystore
      CATALINA_OPTS: "-Xmx4g"
      ENABLE_METRICS: "true"
    networks:
    - gba
    - store-db
    ports:
    - "8080:8080"
    - "9100:9100"
    depends_on:
    - store-db
    restart: always
  store-db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: samplystore
      POSTGRES_PASSWORD: samplystore
    networks:
    - store-db
    ports:
    - "5432:5432"
    volumes:
    - type: volume
      source: store-db-data
      target: /var/lib/postgresql/data
    restart: always
  connector:
    image: akiel/samply.connector:0.1
    environment:
      POSTGRES_HOST: connector-db
      POSTGRES_PASS: samplyconnector
      STORE_URL: http://store:8080/gba-store
      CATALINA_OPTS: "-Xmx1g"
      ENABLE_METRICS: "true"
    networks:
    - gba
    - connector-db
    ports:
    - "8081:8080"
    - "9101:9100"
    depends_on:
    - connector-db
    restart: always
  connector-db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: samplyconnector
      POSTGRES_PASSWORD: samplyconnector
    networks:
    - connector-db
    ports:
    - "5433:5432"
    volumes:
    - type: volume
      source: connector-db-data
      target: /var/lib/postgresql/data
    restart: always
  prometheus:
    image: prom/prometheus:v2.3.2
    networks:
    - gba
    ports:
    - "9090:9090"
    volumes:
    - type: bind
      source: ./prometheus
      target: /etc/prometheus
      read_only: true
    restart: always
  grafana:
    image: grafana/grafana:5.2.2
    environment:
      GF_SESSION_PROVIDER: memory
      GF_LOG_MODE: console
    networks:
    - gba
    ports:
    - "3000:3000"
    volumes:
    - type: volume
      source: grafana-data
      target: /var/lib/grafana
    - type: bind
      source: ./grafana/dashboards
      target: /var/lib/grafana-dashboards
    - type: bind
      source: ./grafana/provisioning
      target: /etc/grafana/provisioning
      read_only: true
    restart: always
networks:
  gba:
    driver: bridge
  store-db:
    driver: bridge
  connector-db:
    driver: bridge
volumes:
  store-db-data:
  connector-db-data:
  grafana-data:
