version: '3.2'
services:
  store:
    image: samply/samply.store:0.2.1-alpha-3
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASS: samplystore
    networks:
    - gba
    ports:
    - "8080:8080"
    depends_on:
    - db
    restart: always
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: samplystore
      POSTGRES_PASSWORD: samplystore
    networks:
    - gba
    ports:
    - "5432:5432"
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/postgresql/data
    restart: always
networks:
  gba:
    driver: bridge
volumes:
  db-data:
